/**
 * `tbd setup` generates the tier agent definitions as two setup surfaces:
 * `claude-agents` (.claude/agents/tbd-*.md) and `codex-agents`
 * (.codex/agents/tbd-*.toml). The files are managed like the other generated
 * surfaces: setup refreshes a stale one on upgrade, keeps a user-owned file
 * with the same name, refuses one written by a newer tbd, and `tbd uninstall`
 * removes the generated ones. Their models and levels come from one table in
 * setup.ts, which must match the dated suggestions in
 * packages/tbd/docs/guidelines/agent-model-tiers.md.
 */

import { spawnSync } from 'node:child_process';
import {
  access,
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  realpath,
  rm,
  writeFile,
} from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { parse as parseYaml } from 'yaml';

import {
  TIER_AGENT_DEFINITIONS,
  TIER_MODELS,
  TIER_MODEL_SUGGESTIONS_AS_OF,
  renderTierAgentDefinition,
} from '../src/cli/commands/setup.js';
import {
  AGENT_INTEGRATION_FORMAT,
  CLAUDE_AGENTS_DIR_REL,
  CODEX_AGENTS_DIR_REL,
} from '../src/lib/integration-paths.js';
import { parseFrontmatter } from '../src/utils/markdown-utils.js';
import { subprocessTestTimeout } from './test-helpers.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TBD_BIN = join(__dirname, '..', 'dist', 'bin.mjs');
const GUIDELINE_PATH = join(__dirname, '..', 'docs', 'guidelines', 'agent-model-tiers.md');

const AGENT_SURFACES = 'claude-agents,codex-agents';
const SKILL_SURFACES = 'portable,agents-md,claude,codex';
const NAMES = ['tbd-strong-max', 'tbd-strong', 'tbd-moderate', 'tbd-fast'];

interface DiagnosticResult {
  name: string;
  status: 'ok' | 'warn' | 'error';
  message?: string;
  suggestion?: string;
}

/** A definition stamped by an older tbd: same marker, older format, other values. */
const STALE_CLAUDE_FAST =
  '---\nname: tbd-fast\ndescription: old\nmodel: sonnet\neffort: low\n---\n' +
  "<!-- DO NOT EDIT: Generated by tbd setup (format=f08).\nRun 'tbd setup' to update.\n-->\n\n" +
  'Old body.\n';
const STALE_CODEX_FAST =
  "# DO NOT EDIT: Generated by tbd setup (format=f08). Run 'tbd setup' to update.\n" +
  'name = "tbd-fast"\ndescription = "old"\nmodel = "gpt-5"\nmodel_reasoning_effort = "low"\n' +
  "developer_instructions = '''\nOld body.\n'''\n";
/** A user's own definition under a tbd name: no ownership marker. */
const USER_OWNED_STRONG =
  '---\nname: tbd-strong\ndescription: mine\nmodel: opus\neffort: high\n---\n\nMy own strong agent.\n';

describe('setup tier agent definitions', { timeout: subprocessTestTimeout(45_000) }, () => {
  let projectDir: string;

  beforeEach(async () => {
    projectDir = await realpath(await mkdtemp(join(tmpdir(), 'tbd-tier-agents-')));
    run(['git', 'init', '--initial-branch=main']);
    run(['git', 'config', 'user.email', 'test@example.com']);
    run(['git', 'config', 'user.name', 'Test']);
  });

  afterEach(async () => {
    await rm(projectDir, { recursive: true, force: true });
  });

  function run(command: [string, ...string[]]): void {
    const result = spawnSync(command[0], command.slice(1), { cwd: projectDir, encoding: 'utf-8' });
    expect(result.status, result.stderr).toBe(0);
  }

  function runTbd(args: string[]): { stdout: string; stderr: string; status: number } {
    const result = spawnSync('node', [TBD_BIN, ...args], {
      cwd: projectDir,
      encoding: 'utf-8',
      env: { ...process.env, FORCE_COLOR: '0', NO_COLOR: '1' },
    });
    return {
      stdout: result.stdout || '',
      stderr: result.stderr || '',
      status: result.status ?? 1,
    };
  }

  function setup(surfaces: string): void {
    const result = runTbd(['setup', '--auto', '--prefix=test', `--surfaces=${surfaces}`]);
    expect(result.status, result.stderr).toBe(0);
  }

  const claudeFile = (name: string) => join(projectDir, CLAUDE_AGENTS_DIR_REL, `${name}.md`);
  const codexFile = (name: string) => join(projectDir, CODEX_AGENTS_DIR_REL, `${name}.toml`);

  async function exists(path: string): Promise<boolean> {
    try {
      await access(path);
      return true;
    } catch {
      return false;
    }
  }

  function tierAgentFindings(): DiagnosticResult[] {
    const result = runTbd(['doctor', '--json']);
    const parsed = JSON.parse(result.stdout) as { integrationChecks: DiagnosticResult[] };
    return parsed.integrationChecks.filter((check) => check.name.includes('tier agents'));
  }

  it('generates the four Claude Code and four Codex definitions (golden)', async () => {
    const result = runTbd(['setup', '--auto', '--prefix=test', `--surfaces=${AGENT_SURFACES}`]);
    expect(result.status, result.stderr).toBe(0);
    expect(result.stdout).toContain('Claude Code tier agents');
    expect(result.stdout).toContain('Codex tier agents');

    expect((await readdir(join(projectDir, CLAUDE_AGENTS_DIR_REL))).sort()).toEqual(
      NAMES.map((name) => `${name}.md`).sort(),
    );
    expect((await readdir(join(projectDir, CODEX_AGENTS_DIR_REL))).sort()).toEqual(
      NAMES.map((name) => `${name}.toml`).sort(),
    );

    expect(await readFile(claudeFile('tbd-strong-max'), 'utf-8')).toMatchInlineSnapshot(`
      "---
      name: tbd-strong-max
      description: tbd strong tier at max reasoning, on fable, the strongest model from the provider. For the hardest or riskiest strong-tier work among senior engineering, security, performance, and correctness reviews, additional review rounds, design decisions, and escalated findings. Spawn it when delegating per tbd shortcut delegate-to-subagents, with a self-contained brief.
      model: fable
      effort: max
      ---
      <!-- DO NOT EDIT: Generated by tbd setup (format=f100).
      Run 'tbd setup' to update.
      -->

      You are tbd-strong-max, a tbd strong-tier sub-agent (fable at max reasoning).
      Work only from the brief you were given. Run the tbd shortcut it names, with
      tbd shortcut <name>, stay inside the write set and other boundaries it states, and
      report in the format it requests. Do not commit, push, run tbd sync, or start
      sub-agents unless the brief says so. The delegation rules are in
      tbd shortcut delegate-to-subagents.
      "
    `);
    expect(await readFile(claudeFile('tbd-strong'), 'utf-8')).toMatchInlineSnapshot(`
      "---
      name: tbd-strong
      description: tbd strong tier at xhigh reasoning, on fable, the strongest model from the provider. For senior engineering, security, performance, and correctness reviews, additional review rounds, design decisions, and escalated findings. Spawn it when delegating per tbd shortcut delegate-to-subagents, with a self-contained brief.
      model: fable
      effort: xhigh
      ---
      <!-- DO NOT EDIT: Generated by tbd setup (format=f100).
      Run 'tbd setup' to update.
      -->

      You are tbd-strong, a tbd strong-tier sub-agent (fable at xhigh reasoning).
      Work only from the brief you were given. Run the tbd shortcut it names, with
      tbd shortcut <name>, stay inside the write set and other boundaries it states, and
      report in the format it requests. Do not commit, push, run tbd sync, or start
      sub-agents unless the brief says so. The delegation rules are in
      tbd shortcut delegate-to-subagents.
      "
    `);
    expect(await readFile(claudeFile('tbd-moderate'), 'utf-8')).toMatchInlineSnapshot(`
      "---
      name: tbd-moderate
      description: tbd moderate tier at xhigh reasoning, on opus, the next-tier model from the provider. For addressing findings (code and test edits, confirming fixes, resolving conflicts). Spawn it when delegating per tbd shortcut delegate-to-subagents, with a self-contained brief.
      model: opus
      effort: xhigh
      ---
      <!-- DO NOT EDIT: Generated by tbd setup (format=f100).
      Run 'tbd setup' to update.
      -->

      You are tbd-moderate, a tbd moderate-tier sub-agent (opus at xhigh reasoning).
      Work only from the brief you were given. Run the tbd shortcut it names, with
      tbd shortcut <name>, stay inside the write set and other boundaries it states, and
      report in the format it requests. Do not commit, push, run tbd sync, or start
      sub-agents unless the brief says so. The delegation rules are in
      tbd shortcut delegate-to-subagents.
      "
    `);
    expect(await readFile(claudeFile('tbd-fast'), 'utf-8')).toMatchInlineSnapshot(`
      "---
      name: tbd-fast
      description: tbd fast tier at medium reasoning, on opus, the next-tier model from the provider. For administrative work (collecting PR and CI state, waiting on CI, bead bookkeeping, posting prepared replies, conflict-free rebases). Spawn it when delegating per tbd shortcut delegate-to-subagents, with a self-contained brief.
      model: opus
      effort: medium
      ---
      <!-- DO NOT EDIT: Generated by tbd setup (format=f100).
      Run 'tbd setup' to update.
      -->

      You are tbd-fast, a tbd fast-tier sub-agent (opus at medium reasoning).
      Work only from the brief you were given. Run the tbd shortcut it names, with
      tbd shortcut <name>, stay inside the write set and other boundaries it states, and
      report in the format it requests. Do not commit, push, run tbd sync, or start
      sub-agents unless the brief says so. The delegation rules are in
      tbd shortcut delegate-to-subagents.
      "
    `);
    expect(await readFile(codexFile('tbd-strong-max'), 'utf-8')).toMatchInlineSnapshot(`
      "# DO NOT EDIT: Generated by tbd setup (format=f100). Run 'tbd setup' to update.

      name = "tbd-strong-max"
      description = "tbd strong tier at max reasoning, on gpt-6-astra, the strongest model from the provider. For the hardest or riskiest strong-tier work among senior engineering, security, performance, and correctness reviews, additional review rounds, design decisions, and escalated findings. Spawn it when delegating per tbd shortcut delegate-to-subagents, with a self-contained brief."
      model = "gpt-6-astra"
      model_reasoning_effort = "max"
      developer_instructions = '''
      You are tbd-strong-max, a tbd strong-tier sub-agent (gpt-6-astra at max reasoning).
      Work only from the brief you were given. Run the tbd shortcut it names, with
      tbd shortcut <name>, stay inside the write set and other boundaries it states, and
      report in the format it requests. Do not commit, push, run tbd sync, or start
      sub-agents unless the brief says so. The delegation rules are in
      tbd shortcut delegate-to-subagents.
      '''
      "
    `);
    expect(await readFile(codexFile('tbd-strong'), 'utf-8')).toMatchInlineSnapshot(`
      "# DO NOT EDIT: Generated by tbd setup (format=f100). Run 'tbd setup' to update.

      name = "tbd-strong"
      description = "tbd strong tier at xhigh reasoning, on gpt-6-astra, the strongest model from the provider. For senior engineering, security, performance, and correctness reviews, additional review rounds, design decisions, and escalated findings. Spawn it when delegating per tbd shortcut delegate-to-subagents, with a self-contained brief."
      model = "gpt-6-astra"
      model_reasoning_effort = "xhigh"
      developer_instructions = '''
      You are tbd-strong, a tbd strong-tier sub-agent (gpt-6-astra at xhigh reasoning).
      Work only from the brief you were given. Run the tbd shortcut it names, with
      tbd shortcut <name>, stay inside the write set and other boundaries it states, and
      report in the format it requests. Do not commit, push, run tbd sync, or start
      sub-agents unless the brief says so. The delegation rules are in
      tbd shortcut delegate-to-subagents.
      '''
      "
    `);
    expect(await readFile(codexFile('tbd-moderate'), 'utf-8')).toMatchInlineSnapshot(`
      "# DO NOT EDIT: Generated by tbd setup (format=f100). Run 'tbd setup' to update.

      name = "tbd-moderate"
      description = "tbd moderate tier at xhigh reasoning, on gpt-5.6-sol, the next-tier model from the provider. For addressing findings (code and test edits, confirming fixes, resolving conflicts). Spawn it when delegating per tbd shortcut delegate-to-subagents, with a self-contained brief."
      model = "gpt-5.6-sol"
      model_reasoning_effort = "xhigh"
      developer_instructions = '''
      You are tbd-moderate, a tbd moderate-tier sub-agent (gpt-5.6-sol at xhigh reasoning).
      Work only from the brief you were given. Run the tbd shortcut it names, with
      tbd shortcut <name>, stay inside the write set and other boundaries it states, and
      report in the format it requests. Do not commit, push, run tbd sync, or start
      sub-agents unless the brief says so. The delegation rules are in
      tbd shortcut delegate-to-subagents.
      '''
      "
    `);
    expect(await readFile(codexFile('tbd-fast'), 'utf-8')).toMatchInlineSnapshot(`
      "# DO NOT EDIT: Generated by tbd setup (format=f100). Run 'tbd setup' to update.

      name = "tbd-fast"
      description = "tbd fast tier at medium reasoning, on gpt-5.6-sol, the next-tier model from the provider. For administrative work (collecting PR and CI state, waiting on CI, bead bookkeeping, posting prepared replies, conflict-free rebases). Spawn it when delegating per tbd shortcut delegate-to-subagents, with a self-contained brief."
      model = "gpt-5.6-sol"
      model_reasoning_effort = "medium"
      developer_instructions = '''
      You are tbd-fast, a tbd fast-tier sub-agent (gpt-5.6-sol at medium reasoning).
      Work only from the brief you were given. Run the tbd shortcut it names, with
      tbd shortcut <name>, stay inside the write set and other boundaries it states, and
      report in the format it requests. Do not commit, push, run tbd sync, or start
      sub-agents unless the brief says so. The delegation rules are in
      tbd shortcut delegate-to-subagents.
      '''
      "
    `);
  });

  it('writes valid frontmatter and TOML fields carrying the tier, model, and level', async () => {
    setup(AGENT_SURFACES);

    for (const def of TIER_AGENT_DEFINITIONS) {
      const claude = await readFile(claudeFile(def.name), 'utf-8');
      const frontmatter = parseFrontmatter(claude);
      expect(frontmatter, def.name).not.toBeNull();
      const fields = parseYaml(frontmatter!) as Record<string, string>;
      expect(fields).toMatchObject({
        name: def.name,
        model: TIER_MODELS.claude[def.tier],
        effort: def.level,
      });
      // The description routes work: tier, model rank, level, and the work it is for.
      expect(fields.description).toContain(`${def.tier} tier`);
      expect(fields.description).toContain(def.level);
      expect(fields.description).toContain(TIER_MODELS.claude[def.tier]);
      expect(fields.description).toContain('delegate-to-subagents');
      // The marker sits after the frontmatter, like every generated SKILL.md.
      expect(claude).toContain(
        `<!-- DO NOT EDIT: Generated by tbd setup (format=${AGENT_INTEGRATION_FORMAT}).`,
      );
      // The body is short and project-neutral: brief, shortcut, report, delegation rules.
      const body = claude.slice(claude.indexOf('-->') + 3);
      expect(body).toContain('tbd shortcut delegate-to-subagents');
      expect(body.split('\n').length).toBeLessThan(12);

      const codex = await readFile(codexFile(def.name), 'utf-8');
      expect(
        codex.startsWith(
          `# DO NOT EDIT: Generated by tbd setup (format=${AGENT_INTEGRATION_FORMAT}).`,
        ),
      ).toBe(true);
      expect(codex).toMatch(new RegExp(`^name = "${def.name}"$`, 'm'));
      expect(codex).toMatch(/^description = ".+"$/m);
      expect(codex).toMatch(new RegExp(`^model = "${TIER_MODELS.codex[def.tier]}"$`, 'm'));
      expect(codex).toMatch(new RegExp(`^model_reasoning_effort = "${def.level}"$`, 'm'));
      expect(codex).toMatch(/^developer_instructions = '''\n[\s\S]+\n'''\n$/m);
      expect(codex).toContain('tbd shortcut delegate-to-subagents');
    }
  });

  it('refreshes stale definitions on upgrade and reports current ones as configured', async () => {
    setup(AGENT_SURFACES);
    const expectedClaude = await readFile(claudeFile('tbd-fast'), 'utf-8');
    const expectedCodex = await readFile(codexFile('tbd-fast'), 'utf-8');

    const again = runTbd(['setup', '--auto', `--surfaces=${AGENT_SURFACES}`]);
    expect(again.status, again.stderr).toBe(0);
    expect(again.stdout).toContain('Already configured');
    expect(again.stdout).not.toContain('Configured integrations');

    await writeFile(claudeFile('tbd-fast'), STALE_CLAUDE_FAST);
    await writeFile(codexFile('tbd-fast'), STALE_CODEX_FAST);
    const upgrade = runTbd(['setup', '--auto', `--surfaces=${AGENT_SURFACES}`]);
    expect(upgrade.status, upgrade.stderr).toBe(0);
    expect(upgrade.stdout).toContain('Configured integrations');
    expect(await readFile(claudeFile('tbd-fast'), 'utf-8')).toBe(expectedClaude);
    expect(await readFile(codexFile('tbd-fast'), 'utf-8')).toBe(expectedCodex);
  });

  it('never overwrites a user-owned file with a tbd name', async () => {
    await mkdir(join(projectDir, CLAUDE_AGENTS_DIR_REL), { recursive: true });
    await writeFile(claudeFile('tbd-strong'), USER_OWNED_STRONG);

    const result = runTbd(['setup', '--auto', '--prefix=test', `--surfaces=${AGENT_SURFACES}`]);
    expect(result.status, result.stderr).toBe(0);
    expect(result.stdout).toContain('user-owned');
    expect(await readFile(claudeFile('tbd-strong'), 'utf-8')).toBe(USER_OWNED_STRONG);
    for (const name of NAMES.filter((n) => n !== 'tbd-strong')) {
      expect(await exists(claudeFile(name)), name).toBe(true);
    }
    for (const name of NAMES) {
      expect(await exists(codexFile(name)), name).toBe(true);
    }

    // A rerun keeps it too, and reports the surface as configured.
    const again = runTbd(['setup', '--auto', `--surfaces=${AGENT_SURFACES}`]);
    expect(again.status, again.stderr).toBe(0);
    expect(again.stdout).toContain('Already configured');
    expect(await readFile(claudeFile('tbd-strong'), 'utf-8')).toBe(USER_OWNED_STRONG);
  });

  it('refuses to rewrite a definition written by a newer tbd', async () => {
    setup(AGENT_SURFACES);
    const current = await readFile(codexFile('tbd-strong'), 'utf-8');
    const tooNew = current.replace(`format=${AGENT_INTEGRATION_FORMAT}`, 'format=f999');
    await writeFile(codexFile('tbd-strong'), tooNew);

    const result = runTbd(['setup', '--auto', `--surfaces=${AGENT_SURFACES}`]);
    expect(result.status).toBe(1);
    expect(result.stdout + result.stderr).toContain('newer tbd');
    expect(await readFile(codexFile('tbd-strong'), 'utf-8')).toBe(tooNew);
  });

  it('is turned off by leaving both surfaces out of --surfaces on that run', async () => {
    const off = runTbd(['setup', '--auto', '--prefix=test', `--surfaces=${SKILL_SURFACES}`]);
    expect(off.status, off.stderr).toBe(0);
    expect(off.stdout).toContain('Skipped (not in --surfaces)');
    expect(off.stdout).toContain('Claude Code tier agents');
    expect(off.stdout).toContain('Codex tier agents');
    expect(await exists(join(projectDir, CLAUDE_AGENTS_DIR_REL))).toBe(false);
    expect(await exists(join(projectDir, CODEX_AGENTS_DIR_REL))).toBe(false);
    // The skill surfaces are unaffected by the split.
    expect(await exists(join(projectDir, '.claude/settings.json'))).toBe(true);
    expect(await exists(join(projectDir, '.codex/hooks.json'))).toBe(true);

    // Each agent surface is selectable on its own, independent of its skill surface.
    const claudeOnly = runTbd(['setup', '--auto', '--surfaces=claude-agents']);
    expect(claudeOnly.status, claudeOnly.stderr).toBe(0);
    expect(await exists(claudeFile('tbd-strong'))).toBe(true);
    expect(await exists(join(projectDir, CODEX_AGENTS_DIR_REL))).toBe(false);
  });

  it('--dry-run reports every write and makes none', async () => {
    const result = runTbd([
      'setup',
      '--auto',
      '--prefix=test',
      '--dry-run',
      `--surfaces=${AGENT_SURFACES}`,
    ]);
    expect(result.status, result.stderr).toBe(0);
    for (const name of NAMES) {
      expect(result.stdout).toMatch(
        new RegExp(`\\[DRY-RUN\\].*[Ww]ould install tier agent definition.*${name}\\.md`),
      );
      expect(result.stdout).toMatch(
        new RegExp(`\\[DRY-RUN\\].*[Ww]ould install tier agent definition.*${name}\\.toml`),
      );
    }
    expect(await exists(join(projectDir, CLAUDE_AGENTS_DIR_REL))).toBe(false);
    expect(await exists(join(projectDir, CODEX_AGENTS_DIR_REL))).toBe(false);
  });

  it('tbd uninstall removes the generated definitions and keeps user-owned ones', async () => {
    await mkdir(join(projectDir, CLAUDE_AGENTS_DIR_REL), { recursive: true });
    await writeFile(claudeFile('tbd-strong'), USER_OWNED_STRONG);
    setup(AGENT_SURFACES);

    const preview = runTbd(['uninstall']);
    expect(preview.status, preview.stderr).toBe(0);
    expect(preview.stdout).toContain('Tier agent definitions: 7 files');

    const result = runTbd(['uninstall', '--confirm']);
    expect(result.status, result.stderr).toBe(0);
    expect(result.stdout).toContain('Removed 7 tier agent definitions');
    for (const name of NAMES.filter((n) => n !== 'tbd-strong')) {
      expect(await exists(claudeFile(name)), name).toBe(false);
    }
    expect(await readFile(claudeFile('tbd-strong'), 'utf-8')).toBe(USER_OWNED_STRONG);
    // An emptied agents directory goes too; one with a user file stays.
    expect(await exists(join(projectDir, CODEX_AGENTS_DIR_REL))).toBe(false);
    expect(await exists(join(projectDir, CLAUDE_AGENTS_DIR_REL))).toBe(true);
  });

  it('doctor reports the definitions only once any exist, and flags stale ones', async () => {
    setup(SKILL_SURFACES);
    // Turned off on this run: no finding, so doctor output does not nag.
    expect(tierAgentFindings()).toEqual([]);

    setup(AGENT_SURFACES);
    expect(tierAgentFindings()).toEqual([
      expect.objectContaining({
        name: 'Claude Code tier agents',
        status: 'ok',
        message: 'current',
      }),
      expect.objectContaining({ name: 'Codex tier agents', status: 'ok', message: 'current' }),
    ]);

    await writeFile(claudeFile('tbd-fast'), STALE_CLAUDE_FAST);
    await rm(codexFile('tbd-moderate'));
    await writeFile(claudeFile('tbd-strong'), USER_OWNED_STRONG);
    const findings = tierAgentFindings();
    expect(findings[0]).toMatchObject({
      name: 'Claude Code tier agents',
      status: 'warn',
      message: 'stale managed file',
      suggestion: 'Run: tbd setup --auto --surfaces=claude-agents',
    });
    expect(findings[1]).toMatchObject({
      name: 'Codex tier agents',
      status: 'warn',
      message: 'missing',
      suggestion: 'Run: tbd setup --auto --surfaces=codex-agents',
    });
    // Doctor changes nothing.
    expect(await readFile(claudeFile('tbd-fast'), 'utf-8')).toBe(STALE_CLAUDE_FAST);

    // After setup, the override is reported as kept rather than as a problem.
    setup(AGENT_SURFACES);
    expect(tierAgentFindings()[0]).toMatchObject({
      status: 'ok',
      message: 'current (1 user-owned file kept)',
    });
  });

  it('too-new definitions are an error for doctor', async () => {
    setup(AGENT_SURFACES);
    const current = await readFile(claudeFile('tbd-moderate'), 'utf-8');
    await writeFile(
      claudeFile('tbd-moderate'),
      current.replace(`format=${AGENT_INTEGRATION_FORMAT}`, 'format=f999'),
    );
    expect(tierAgentFindings()[0]).toMatchObject({
      name: 'Claude Code tier agents',
      status: 'error',
      message: `managed file uses newer integration format f999 (supported: ${AGENT_INTEGRATION_FORMAT})`,
    });
  });
});

describe('tier agent definitions match the agent-model-tiers guideline', () => {
  it('uses the dated suggestions table for models and levels', async () => {
    const guideline = await readFile(GUIDELINE_PATH, 'utf-8');

    const heading = /^## Suggested Models as of (\d{4}-\d{2}-\d{2})$/mu.exec(guideline);
    expect(heading?.[1]).toBe(TIER_MODEL_SUGGESTIONS_AS_OF);

    const table = guideline.slice(heading!.index);
    for (const tier of ['strong', 'moderate', 'fast'] as const) {
      const row = new RegExp(`^\\| ${tier} \\| (.+?) \\| (.+?) \\|$`, 'mu').exec(table);
      expect(row, `${tier} row`).not.toBeNull();
      const [, anthropic, openai] = row!;
      const identifiers = (cell: string) => [...cell.matchAll(/`([^`]+)`/gu)].map((m) => m[1]);
      const [anthropicModel, ...anthropicLevels] = identifiers(anthropic!);
      const [openaiModel, ...openaiLevels] = identifiers(openai!);
      expect(anthropicModel).toBe(TIER_MODELS.claude[tier]);
      expect(openaiModel).toBe(TIER_MODELS.codex[tier]);
      for (const def of TIER_AGENT_DEFINITIONS.filter((d) => d.tier === tier)) {
        expect(anthropicLevels, `${def.name} level`).toContain(def.level);
        expect(openaiLevels, `${def.name} level`).toContain(def.level);
      }
    }
  });

  it('lists the same four definitions and levels as the guideline', async () => {
    const guideline = await readFile(GUIDELINE_PATH, 'utf-8');
    const listed = [...guideline.matchAll(/`(tbd-[a-z-]+)` \(`([a-z]+)`\)/gu)].map((m) => ({
      name: m[1],
      level: m[2],
    }));
    expect(listed).toEqual(TIER_AGENT_DEFINITIONS.map(({ name, level }) => ({ name, level })));
  });

  it('renders every definition from the one table', () => {
    for (const def of TIER_AGENT_DEFINITIONS) {
      expect(renderTierAgentDefinition('claude', def)).toContain(`effort: ${def.level}`);
      expect(renderTierAgentDefinition('codex', def)).toContain(
        `model_reasoning_effort = "${def.level}"`,
      );
    }
  });
});
