import type { Stats } from 'node:fs';
import { lstat, readFile } from 'node:fs/promises';

import { CLIError } from './errors.js';

export type ManagedArtifactState = 'current' | 'stale' | 'missing' | 'user-owned' | 'too-new';

export interface ManagedArtifactInspection {
  state: ManagedArtifactState;
  format?: string;
}

export interface InspectManagedArtifactOptions {
  path: string;
  expectedContent: string;
  ownershipMarker: string;
  supportedFormat: string;
  selectManagedContent?: (content: string) => string;
}

/** Byte span occupied by one complete marker-delimited managed block. */
export interface ManagedBlockLocation {
  /** Offset of the begin marker itself; leading indentation remains in the prefix. */
  start: number;
  /** Exclusive offset after the end marker line, including its line ending when present. */
  end: number;
}

export interface SafeManagedArtifactTargetOptions {
  /** Accept ENOENT when the caller is allowed to create the file. */
  allowMissing?: boolean;
}

/**
 * Refuse managed-file targets that can redirect or invalidate a project-local write.
 * `lstat` is deliberate: `stat` and `realpath` follow a symlink before the caller can
 * enforce that AGENTS.md itself is a regular file in the selected project.
 */
export async function assertSafeManagedArtifactTarget(
  path: string,
  options: SafeManagedArtifactTargetOptions = {},
): Promise<void> {
  let stats: Stats;
  try {
    stats = await lstat(path);
  } catch (error) {
    if (isErrorWithCode(error, 'ENOENT')) {
      if (options.allowMissing) {
        return;
      }
      throw new CLIError(
        `Refusing to update ${path}: the file does not exist. Create it as a regular file and retry.`,
      );
    }
    throw error;
  }

  if (stats.isFile()) {
    return;
  }

  throw new CLIError(
    `Refusing to update ${path}: expected a regular file, but found ${managedTargetKind(stats)}. ` +
      'Replace it with a regular file inside the project and retry.',
  );
}

/**
 * Return the numeric portion of an integration format stamp. Stamps written
 * through tbd 0.9.0 are two digits (f01..f08, the repository format of the day);
 * later stamps are three digits (f100 and up). Numeric order works across both:
 * `f100` is 100 against 0.9.0's ceiling of 8, so 0.9.0 refuses the surface
 * through the comparison it already ships, with no change to 0.9.0.
 */
export function integrationFormatNumber(format: string): number {
  return Number.parseInt(format.replace(/^f/, ''), 10);
}

/**
 * A line that opens one of tbd's own markers, in any generated surface: the
 * AGENTS.md block (`<!-- BEGIN TBD …`), a generated skill (`<!-- DO NOT EDIT: …`),
 * or a tier agent definition, where the same marker is a TOML or Markdown comment.
 */
const STAMP_LINE = /^(?:<!--|#|\/\/)?\s*(?:BEGIN TBD |DO NOT EDIT: Generated by tbd setup)/;

/**
 * Read the `format=fN...` stamp from generated integration content. The regex and
 * the numeric comparison above are what every released tbd uses, so a new stamp
 * must parse here as a number above the older release's ceiling.
 *
 * Only a line that opens one of tbd's own markers counts. Reading the first
 * `format=` anywhere in the file let a line of prose quoting an older stamp stand
 * in for the real one, and the guard that stops an older tbd from rewriting a
 * newer surface then permitted the write.
 */
export function parseManagedIntegrationFormat(content: string): string | null {
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!STAMP_LINE.test(trimmed)) {
      continue;
    }
    const match = /format=f(\d+)/.exec(trimmed);
    if (match?.[1]) {
      return `f${match[1]}`;
    }
  }
  return null;
}

/**
 * Inspect a tbd-owned text artifact without changing it.
 *
 * Setup dry runs and doctor diagnostics share this comparison so they cannot
 * disagree about whether the generated file is current, stale, or unsafe to
 * replace.
 */
export async function inspectManagedArtifact(
  options: InspectManagedArtifactOptions,
): Promise<ManagedArtifactInspection> {
  let existing: string;
  try {
    existing = await readFile(options.path, 'utf-8');
  } catch (error) {
    if (isErrorWithCode(error, 'ENOENT')) {
      return { state: 'missing' };
    }
    throw error;
  }

  let managedContent: string;
  if (options.selectManagedContent) {
    managedContent = options.selectManagedContent(existing);
    if (managedContent.length === 0) {
      return { state: 'user-owned' };
    }
  } else {
    if (!existing.includes(options.ownershipMarker)) {
      return { state: 'user-owned' };
    }
    managedContent = existing;
  }
  const format = parseManagedIntegrationFormat(managedContent) ?? 'f01';
  if (integrationFormatNumber(format) > integrationFormatNumber(options.supportedFormat)) {
    return { state: 'too-new', format };
  }

  return {
    state: sameManagedContent(managedContent, options.expectedContent) ? 'current' : 'stale',
    format,
  };
}

/**
 * Compare managed content ignoring line endings. Every generator emits LF, while a
 * Windows checkout holds CRLF, so a raw comparison calls each managed surface stale on
 * that platform; setup then writes an LF block into a CRLF file, which leaves the file
 * modified with an empty diff and stale again after the next write.
 */
function sameManagedContent(actual: string, expected: string): boolean {
  return actual === expected || toLf(actual) === toLf(expected);
}

function toLf(text: string): string {
  return text.replace(/\r\n/gu, '\n');
}

/**
 * Extract one marker-delimited managed block, including both marker lines. A
 * marker counts only as its own line, so a line of prose quoting one cannot move
 * the block's boundaries (and with them the stamp this file reads).
 */
export function extractManagedBlock(
  content: string,
  beginMarker: string,
  endMarker: string,
): string {
  const location = locateManagedBlock(content, beginMarker, endMarker);
  if (!location) {
    return '';
  }
  return content.slice(location.start, location.end).trimEnd() + '\n';
}

/**
 * Locate one complete managed block using marker lines, never marker substrings in
 * prose or inline code. The returned end is suitable for exact prefix/block/suffix
 * replacement, so readers and writers share one boundary calculation.
 */
export function locateManagedBlock(
  content: string,
  beginMarker: string,
  endMarker: string,
): ManagedBlockLocation | null {
  const start = indexOfMarkerLine(content, beginMarker, false);
  if (start < 0) {
    return null;
  }
  const endOffset = indexOfMarkerLine(content.slice(start), endMarker, true);
  if (endOffset < 0) {
    return null;
  }

  const endStart = start + endOffset;
  const nextNewline = content.indexOf('\n', endStart + endMarker.length);
  return {
    start,
    end: nextNewline < 0 ? content.length : nextNewline + 1,
  };
}

/**
 * Offset of the first marker line, or -1. Begin markers are stable prefixes
 * whose metadata may change; end markers are complete, exact lines.
 */
function indexOfMarkerLine(content: string, marker: string, exact: boolean): number {
  let offset = 0;
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    const isMarker = exact
      ? trimmed === marker
      : trimmed.startsWith(marker) && trimmed.endsWith('-->');
    if (isMarker) {
      return offset + (line.length - line.trimStart().length);
    }
    offset += line.length + 1;
  }
  return -1;
}

function isErrorWithCode(error: unknown, code: string): boolean {
  return (
    error instanceof Error &&
    'code' in error &&
    typeof error.code === 'string' &&
    error.code === code
  );
}

/** Bounded description for diagnostics; never render device metadata or link targets. */
function managedTargetKind(stats: Stats): string {
  if (stats.isSymbolicLink()) {
    return 'a symbolic link';
  }
  if (stats.isDirectory()) {
    return 'a directory';
  }
  if (stats.isSocket()) {
    return 'a socket';
  }
  if (stats.isFIFO()) {
    return 'a FIFO';
  }
  if (stats.isBlockDevice()) {
    return 'a block device';
  }
  if (stats.isCharacterDevice()) {
    return 'a character device';
  }
  return 'a non-regular filesystem entry';
}
